apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: twinsight
  labels:
    app: user-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-server
  template:
    metadata:
      labels: 
        app: user-server
    spec:
      containers:
      - name: user-server
        imagePullPolicy: Always
        image: registry.thedutchmc.nl/twinsight-user-server:latest
        ports:
        - containerPort: 8070
          name: api
        env:
        - name: MYSQL_HOST
          value: mariadb.labs.thedutchmc.nl
        - name: MYSQL_DATABASE
          value: twinsight-prod-user-server
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: user-server-mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: content-manager
              key: user-server-mysql-password
        - name: LOGIN_SERVER_HOST
          value: https://login.api.twinsight.media
---
apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: twinsight
spec:
  selector:
    app: user-server
  ports:
  - protocol: TCP
    name: api
    port: 8070
    targetPort: 8070
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-server
  namespace: twinsight
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - user.api.twinsight.media
    secretName: twinsight-media-tls
  rules:
  - host: user.api.twinsight.media
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-server
            port:
              number: 8070
