apiVersion: v1
kind: Secret
metadata:
  name: catexplorer-iscsi-chap
  namespace: default
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: "Y2F0ZXhwbG9yZXIK"
  node.session.auth.password: "cjg3Q2c2eW1lM0tUbUoK"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: catexplorer-pv
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.2.4:3260
    iqn: 'iqn.2021-03.storage.thedutchmc.nl:catexplorer'
    lun: 1
    fsType: 'ext4'
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: catexplorer-iscsi-chap
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catexplorer-pvc
spec:
  volumeName: catexplorer-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catexplorer-deployment
  labels:
    app: catexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catexplorer
  template:
    metadata:
      labels:
        app: catexplorer
    spec:
      containers:
      - name: catexplorer
        image: thedutchmc/catexplorer:latest
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: catexplorer
              key: token
        volumeMounts:
        - name: catexplorer-pics
          mountPath: /data
      volumes:
       - name: catexplorer-pics
         persistentVolumeClaim:
           claimName: catexplorer-pvc
