apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver-deployment
  namespace: mrfriendly
  labels:
    app: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: registry.thedutchmc.nl/authserver:latest
        ports:
        - name: api
          containerPort: 8080
        env:
        - name: "GOOGLE_CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: authserver
              key: google_client_id
        - name: "GOOGLE_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: authserver
              key: google_client_secret
        - name: "HOST"
          value: "https://auth.api.mrfriendly.nl"
        - name: "MYSQL_HOST"
          value: "192.168.1.222"
        - name: "MYSQL_DATABASE"
          value: "authserver"
        - name: "MYSQL_USERNAME"
          valueFrom:
            secretKeyRef:
              name: authserver
              key: mysql_username
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: authserver
              key: mysql_password
---
apiVersion: v1
kind: Service
metadata:
  name: authserver-service
  namespace: mrfriendly
spec:
  selector:
    app: authserver
  ports:
  - protocol: TCP
    name: api
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mrfriendly-auth-api
  namespace: mrfriendly
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - auth.api.mrfriendly.nl
    secretName: mrfriendly-tls
  rules:
  - host: auth.api.mrfriendly.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authserver-service
            port:
              number: 8080
