apiVersion: v1
kind: ConfigMap
metadata:
  name: reactioner-bot
  namespace: prodlab
data:
  config: |
    botToken: FROM_ENV
    commandPrefix: '%'
    messageEntries:
    - messageId: '851879298650210315'
      reactionEntries:
      - reactionName: purple_heart
        roleId: 738026804815724684
      - reactionName: blue_heart
        roleId: 738026729549070426
      - reactionName: yellow_heart
        roleId: 738026881697185883
      - reactionName: green_heart
        roleId: 738026938236403852
    - messageId: '851879671955718146'
      reactionEntries:
      - reactionName: egg
        roleId: 851883917127843921
      - reactionName: chicken
        roleId: 851883870965858344
    - messageId: '851882998030663711'
      reactionEntries:
      - reactionName: frog
        roleId: 644642055896694804
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactioner-bot
  namespace: prodlab
  labels:
    app: reactioner-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactioner-bot
  template:
    metadata:
      labels:
        app: reactioner-bot
    spec:
      automountServiceAccountToken: false
      containers:
      - name: reactioner-bot
        imagePullPolicy: Always
        image: docker-registry.k8s.array21.dev/reactioner-bot:latest
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: reactioner-bot
              key: bot-token
        volumeMounts:
        - name: config
          mountPath: /config/
      volumes:
      - name: config
        configMap:
          name: reactioner-bot
          items:
          - key: config
            path: config.yml
